services:
  - type: web
    name: cirser-backend
    env: docker
    dockerContext: backend
    envVars:
      - key: PROJECT_NAME
        value: Cirser
      - key: DATABASE_URL
        fromDatabase:
          name: cirser-db
          property: connectionString
      - key: AI_SERVICE_URL
        value: http://localhost:10000/v1
      - key: HF_API_KEY
        sync: false

databases:
  - name: cirser-db
    databaseName: cirser
    user: cirser_user
    plan: free
